### ISSUE TITLE
Package ( does not exist.

### ISSUE THREAD

**Issue by burtonsamograd** [vsedach/Parenscript#20] opened 2015-03-25 15:02 UTC
When trying to load parenscript @ 101b09ed5bec095a72068ef36afc080620b5ff42:

CL-USER> (asdf:operate 'asdf:load-op 'parenscript)
; compiling file "/home/burton/common-lisp/lib/Parenscript/src/package.lisp" (written 29 JAN 2015 09:42:45 AM):
; compiling (IN-PACKAGE #:CL)
; compiling (PUSHNEW :PARENSCRIPT ...)
; compiling (UNLESS (EDITOR-HINTS.NAMED-READTABLES:FIND-READTABLE :PARENSCRIPT) ...)
; compiling (EDITOR-HINTS.NAMED-READTABLES:IN-READTABLE :PARENSCRIPT)
; compiling |(DEFPACKAGE|
; compiling #:PARENSCRIPT
; 
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Package ( does not exist.
;   
;       Line: 14, Column: 7, File-Position: 343
;   
;       Stream: #<SB-SYS:FD-STREAM
;                 for "file /home/burton/common-lisp/lib/Parenscript/src/package.lisp"
;                 {10133948B3}>
; compilation aborted after 0:00:00.027
; 
; compilation unit aborted
;   caught 3 fatal ERROR conditions
;   caught 1 ERROR condition
; Evaluation aborted on #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {10031F4823}>.

The |(DEFPACKAGE| looks very suspect but I can't seem to figure out what is wrong.

**Comment by agrostis** [comment] 2015-03-25 22:06
May I know what Lisp implementation you are using?

**Comment by burtonsamograd** [comment] 2015-03-26 00:08
A relatively recent SBCL.

**Comment by agrostis** [comment] 2015-03-26 13:03
1.2.6? 1.2.7? 1.2.8? 1.2.9?

**Comment by burtonsamograd** [comment] 2015-03-26 18:34
It was around 1.2.6 (built from git sources).  I've upgraded to 1.2.9 and still get the same error:

CL-USER> (require 'parenscript)
; compiling file "/home/burton/common-lisp/lib/Parenscript/src/package.lisp" (written 25 MAR 2015 09:01:43 AM):
; compiling (IN-PACKAGE #:CL)
; compiling (PUSHNEW :PARENSCRIPT ...)
; compiling (UNLESS (EDITOR-HINTS.NAMED-READTABLES:FIND-READTABLE :PARENSCRIPT) ...)
; compiling (EDITOR-HINTS.NAMED-READTABLES:IN-READTABLE :PARENSCRIPT)
; compiling |(DEFPACKAGE|
; compiling #:PARENSCRIPT
; 
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Package ( does not exist.
;   
;       Line: 14, Column: 7, File-Position: 343
;   
;       Stream: #<SB-SYS:FD-STREAM
;                 for "file /home/burton/common-lisp/lib/Parenscript/src/package.lisp"
;                 {10064A3733}>
; compilation aborted after 0:00:00.004
ASDF could not load parenscript because
COMPILE-FILE-ERROR while
compiling #<CL-SOURCE-FILE "parenscript" "src" "package">.

**Comment by nimiux** [comment] 2015-04-07 21:05
Same thing here with SBCL-1.2.9.
I've managed to compile the package by commenting out all references to the read-namedtables package. Then, the first time I (require :parescript) I get:

...
; compiling file "/usr/share/common-lisp/source/parenscript/src/package.lisp" (written 07 APR 2015 10:44:45 PM):
; compiling (IN-PACKAGE #:CL)
; compiling (PUSHNEW :PARENSCRIPT ...)
; compiling (UNLESS (EDITOR-HINTS.NAMED-READTABLES:FIND-READTABLE :PARENSCRIPT) ...)ASDF could not load parenscript because
The value #<FDEFINITION for SB-IMPL::READ-LIST>
is not of type
  (OR FUNCTION SYMBOL)..

debugger invoked on a TYPE-ERROR in thread
#<THREAD "main thread" RUNNING {1002D364A3}>:
  The value #<FDEFINITION for SB-IMPL::READ-LIST>
  is not of type
    (OR FUNCTION SYMBOL).

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry
                                     compiling #<CL-SOURCE-FILE "parenscript" "src" "package">.
  1: [ACCEPT                       ] Continue, treating
                                     compiling #<CL-SOURCE-FILE "parenscript" "src" "package">
                                     as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  4: [ABORT                        ] Exit debugger, returning to top level.

(SET-MACRO-CHARACTER #\( #<FDEFINITION for SB-IMPL::READ-LIST> NIL #<NAMED-READTABLE :PARENSCRIPT {1005BEB5A3}>) [tl,external]
0] 

Then I hit 0 (RETRY) and the package compiles.

**Comment by nimiux** [comment] 2015-04-30 12:42
I've managed to (require) it. I've used:
* sbcl-1.2.11
* Latest named-readtables code pulled from https://github.com/melisgl/named-readtables
* parenscript-2.5 downloadable from https://common-lisp.net/project/parenscript/

**Comment by agrostis** [comment] 2015-05-17 16:46
Right; it seems to be a problem in Named-Readtables caused by an inconsistency introduced by SBCL 1.1.18. It's been fixed by http://sourceforge.net/p/sbcl/sbcl/ci/c29b4b7e891df2cad98d136976a62ffcf7c184a3 and https://github.com/melisgl/named-readtables/commit/d72ad1e716987e473fd25993fa5c2614bb4913fa . I understand that you should be able to compile the repository version of Parenscript (no need to downgrade to 2.5) with the repository version of Named-Readtables and any SBCL upward from 1.1.18.

**Closed by agrostis** 2015-05-17 16:46 UTC
